---
- name: Include secret vars (airflow credentials)
  include_vars:
    file: ../../../vars_secret/airflow.yaml
  tags:
    - airflow_update_logins
    - airflow_update_connections

- name: ensure remote folder for airflow exists
  become: "{{ should_become }}"
  file:
    path: '{{ remote_airflow_folder }}'
    state: directory
    owner: '{{ owner }}'

- name: Copy airflow dockerfile to remote
  template:
    src: Dockerfile_airflow.j2
    dest: '{{ remote_airflow_folder }}/Dockerfile_airflow'

- name: Copy airflow_requirements.txt on remote into airflow build folder
  shell: cp {{ home_path }}/IdeaProjects/onsite_project/requirements.txt {{ remote_airflow_folder }}/airflow_requirements.txt

- name: Copy postgres dockerfile to remote
  template:
    src: Dockerfile_postgres_meta_db.j2
    dest: '{{remote_airflow_folder}}/Dockerfile_postgres_meta_db'

- name: Copy postgresql.conf to remote
  template:
    src: postgresql_conf.j2
    dest: '{{ remote_airflow_folder }}/postgresql.conf'

- name: Copy currency csv
  copy:
    src: ../files/currency.csv
    dest: "{{ remote_airflow_folder }}/currency.csv"

- include_tasks: build_core.yaml
  when: airflow_components == 'core'
